server:
  port: 80

#wecheat configure
wx:
  app-id: wx1078f468a21b6695
  app-secret: 9ed8789e848883783e529cc5b06e67c4
  app-get-access-token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential
  app-send-msg: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
  #hito
  app-yy-tips: https://v1.hitokoto.cn/?c=j
  #baidu天气接口ack小程序端
  #app_baidu_ack: 2LbuCFS1wH3gUyVTCepmK7474nkyqrww
  #服务端
  app-baidu-ack: Ov8sbVDiik3735tPm1EEj6CkdlpGe0q8


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-0cofr8ke.sql.tencentcdb.com:20620/partnerpush
    username: root
    password: Jyztmdshuai666

